"""Remove mg field from samples table

Revision ID: 2ec85993e7fe
Revises: b39a553d1f4d
Create Date: 2024-07-22 00:32:14.410235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ec85993e7fe'
down_revision = 'b39a553d1f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'mg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('mg', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
