"""Add request name request model

Revision ID: 39cb81ee1584
Revises: 4b4eaa0176af
Create Date: 2024-08-11 22:48:32.520522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cb81ee1584'
down_revision = '4b4eaa0176af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('request_name', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'request_name')
    # ### end Alembic commands ###
