"""Add recovery, sample_ids, nucleo_ids, and total_cost to requests

Revision ID: 4b4eaa0176af
Revises: be937ce11839
Create Date: 2024-08-11 22:15:38.645250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b4eaa0176af'
down_revision = 'be937ce11839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('recovery', sa.String(length=3), nullable=False))
    op.add_column('requests', sa.Column('sample_ids', sa.String(length=256), nullable=False))
    op.add_column('requests', sa.Column('nucleo_ids', sa.String(length=256), nullable=False))
    op.add_column('requests', sa.Column('total_cost', sa.Float(), nullable=False))
    op.drop_column('requests', 'request_name')
    op.drop_column('requests', 'sample_name')
    op.drop_column('requests', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.add_column('requests', sa.Column('sample_name', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('requests', sa.Column('request_name', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('requests', 'total_cost')
    op.drop_column('requests', 'nucleo_ids')
    op.drop_column('requests', 'sample_ids')
    op.drop_column('requests', 'recovery')
    # ### end Alembic commands ###
