"""Add price field to Sample model

Revision ID: 516a411996e2
Revises: 2ec85993e7fe
Create Date: 2024-08-04 02:43:01.736103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '516a411996e2'
down_revision = '2ec85993e7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('project_name', sa.String(length=64), nullable=False))
    op.add_column('requests', sa.Column('solvent_name', sa.String(length=64), nullable=False))
    op.add_column('requests', sa.Column('sample_preparation_name', sa.String(length=64), nullable=False))
    op.add_column('requests', sa.Column('sample_name', sa.String(length=64), nullable=False))
    op.drop_constraint('requests_ibfk_5', 'requests', type_='foreignkey')
    op.drop_constraint('requests_ibfk_3', 'requests', type_='foreignkey')
    op.drop_constraint('requests_ibfk_6', 'requests', type_='foreignkey')
    op.drop_constraint('requests_ibfk_4', 'requests', type_='foreignkey')
    op.drop_constraint('requests_ibfk_2', 'requests', type_='foreignkey')
    op.drop_column('requests', 'solvent_id')
    op.drop_column('requests', 'project_id')
    op.drop_column('requests', 'sample_preparation_id')
    op.drop_column('requests', 'sample_id')
    op.add_column('samples', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'price')
    op.add_column('requests', sa.Column('sample_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('sample_preparation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('solvent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('requests_ibfk_2', 'requests', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('requests_ibfk_4', 'requests', 'solvents', ['solvent_id'], ['id'])
    op.create_foreign_key('requests_ibfk_6', 'requests', 'sample_preparation', ['sample_preparation_id'], ['id'])
    op.create_foreign_key('requests_ibfk_3', 'requests', 'samples', ['sample_id'], ['id'])
    op.create_foreign_key('requests_ibfk_5', 'requests', 'user_accounts', ['user_rut'], ['rut'])
    op.drop_column('requests', 'sample_name')
    op.drop_column('requests', 'sample_preparation_name')
    op.drop_column('requests', 'solvent_name')
    op.drop_column('requests', 'project_name')
    # ### end Alembic commands ###
