"""Add estado to requests

Revision ID: 53a75549c0e1
Revises: d2cd573fd268
Create Date: 2024-08-04 03:03:41.538912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a75549c0e1'
down_revision = 'd2cd573fd268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('estado', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'estado')
    # ### end Alembic commands ###
