"""Added fondo field to project table

Revision ID: 9f9e37e0d295
Revises: d63d26739ed3
Create Date: 2024-07-18 02:00:03.741893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9e37e0d295'
down_revision = 'd63d26739ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('fondo', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'fondo')
    # ### end Alembic commands ###
