"""update fields requests model

Revision ID: d2cd573fd268
Revises: 516a411996e2
Create Date: 2024-08-04 02:52:26.590990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cd573fd268'
down_revision = '516a411996e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'user_name')
    # ### end Alembic commands ###
