"""Add machine_name to Request

Revision ID: fe2f15b2be90
Revises: b52b29d0e6cf
Create Date: 2024-09-01 13:01:29.879857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2f15b2be90'
down_revision = 'b52b29d0e6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('machine_name', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'machine_name')
    # ### end Alembic commands ###
